### PR TITLE
Support symlink

### PR DESCRIPTION
**Pull request by moajo**
Hi!

This PR is as implementation of #6 
Support for symlink file/dir archive and Excludes option.
All symlink files will be resolves and included in the archive file.

### CODE REVIEW

**Comment by no-acl** [comment]
Is there any chance this could be merged in? 
It would solve an annoying problem we have

**Comment by moajo** [comment]
This branch was out-of-date to master for a few months, so I rebased onto master and rebuilt this PR.

And since Travis' symlink feature wasn't enabled in the Windows environment, I modified the travis.yml and passed all the tests.

@wilkmaia 
Is it possible that this PR will be merged?

**Comment by barneyparker** [comment]
Hi, sorry to hassle maintainers, but this feels like its ready (or extremely close to it) for merge, and @moajo has done their best to keep it up to date with master/main.  its not a huge bug, but it is a really awkward problem to work around and while a fix is present it seems a shame not to get it merged.

Is there anything anyone can do to get this prioritised for a merge?

I actually came across this because i have had a lot of issues with archive_file zip files creating oddly malformed symlinks.  I was going to take a stab at fixing the issue, but given my major lack of Go knowledge I was really happy to find that someone better at this than me had already solved the problem!

It would really great to get this bug squashed :)

**Comment by gthieleb** [comment]
@moajo A question about your PR. 

For AWS lambda I am using virtualenv within docker container (using the official lambda image) that creates some symlinks in `/venv/path/bin` .

Outside the container these links looks like they are broken.

```
ls -la layers/packages/ansible/bin/python
lrwxrwxrwx 1 root root 23 Dez  3 07:56 layers/packages/ansible/bin/python -> /var/lang/bin/python3.8
```
Does your implementation covers archiving these kind of symlinks?

**Comment by bendbennett** [comment]
@moajo as the _archive_ provider has now been migrated from SDKv2 to the [Terraform Plugin Framework](https://developer.hashicorp.com/terraform/plugin/framework), I have incorporated your changes from this PR into #183 and added you as a coauthor as the vast majority of the changes are in this PR. The only significant change I made in #183 was the handling of symbolic links that are using an absolute path. If you would rather rebase this PR on the latest main then please go ahead and I will close out #183. Thank you very much for your contribution.

**Comment by bendbennett** [comment]
Implemented in #183 and released in [v2.4.0](https://github.com/hashicorp/terraform-provider-archive/releases/tag/v2.4.0).

**Pull request closed without merging**
