### PR TITLE
Support glob matching for zip excludes

### LINKED ISSUE #62: Support glob paths in archive_file data source excludes
It would be really handy if `data.archive_file` supported glob matching for `excludes`. This would enable configurations such as:
```hcl
data "archive_file" "zip" {
  type        = "zip"
  output_path = "./myzip.zip"
  source_dir  = "."
  excludes    = ["**/.git"]
}
```
in order to exclude all `.git` directories from the archive.

The glob matching should ideally support the well known `**` syntax meaning _0 or more directories_

### Affected Resource(s)
- `data.archive_file`

### PR DESCRIPTION
**Pull request by mbamber**
Add support for excluding files and directories using a glob expression
supplied to `excludes`. In particular, `*` matches any character (except
the directory separator) any number of times, and `**` matches any
character including the directory separator any number of times.

Fixes #62

### CODE REVIEW

**Comment by mbamber** [comment]
This is a copy of #63 which cannot be reopened for some reason

**Comment by mbamber** [comment]
I've finally gotten around to rebasing this so there are no conflicts. This is now ready for review

**Comment by KieranWynn** [comment]
Is this ready to be merged? Would be super handy.

**Comment by cmeury** [comment]
This PR is getting quite old, but would be very useful for lots of people -- any chance someone could take a look?

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Pull request closed without merging**
