### PR TITLE
tree-wide: fix references to the terraform-providers organization

### PR DESCRIPTION
**Pull request by flokli**
`terraform-provider-archive` has been moved to the `hashicorp`
organization.

### CODE REVIEW

**Comment by flokli** [comment]
@appilon could you take a look at this, and the other PRs?

They all fix broken references after the org transfer:

 - https://github.com/hashicorp/terraform-provider-archive/pull/67
 - https://github.com/hashicorp/terraform-provider-local/pull/40
 - https://github.com/hashicorp/terraform-provider-null/pull/43
 - https://github.com/hashicorp/terraform-provider-template/pull/79
 - https://github.com/hashicorp/terraform-provider-external/pull/41
 - https://github.com/hashicorp/terraform-provider-http/pull/40
 - https://github.com/hashicorp/terraform-provider-tls/pull/71
 - https://github.com/hashicorp/terraform-provider-dns/pull/101
 - https://github.com/hashicorp/terraform-provider-random/pull/107

Thanks!

**Comment by flokli** [comment]
ping ;-)

**Comment by kmoe** [comment]
Thank you for the PR.

We do not support importing Terraform providers as Go modules, so it is not necessary to update the module path for this provider. Please see our [best practice documentation](https://www.terraform.io/docs/extend/best-practices/depending-on-providers.html#do-not-import-providers-as-go-modules).

While we appreciate the effort that goes into preparing PRs, there is always a tradeoff between benefit and cost. In this case, the proposed change would break in-flight pull requests for this provider, creating extra vendor diffs and extra work for our contributors. We therefore will not merge this PR at this time.

If the module path is causing issues with something besides importing the provider, we'd love to hear more about it. Reply to this issue and let us know what you're trying to do, and we'll look into it.

**Comment by flokli** [comment]
Thanks for getting back to me on this.

> If the module path is causing issues with something besides importing the provider, we'd love to hear more about it. Reply to this issue and let us know what you're trying to do, and we'll look into it.

I don't import Terraform providers as a go module in my code, but the build tooling and packaging code around fails to build with the wrong names. Please see the referencing issue https://github.com/NixOS/nixpkgs/pull/83279 for details and the other issues linked in https://github.com/hashicorp/terraform-provider-archive/pull/67#issuecomment-619273413 for the fallout currently required to get them to build.

I don't really see how this can largely affect other in-flight pull requests - it shouldn't change any vendor diffs in this repo, and this is mostly to be consistent with where the code now lives.

**Comment by flokli** [comment]
Also note the current approach seems to be named the "module name workaround", and fixing the references, as proposed here and in the other 8 PRs seems to be preferred, as per https://github.com/hashicorp/terraform-provider-helm/pull/522:

> Instead of using the module name workaround from step 7 of the migration RFC
(https://docs.google.com/document/d/1PQFAhpTgUhHcZxIIWapNsa0UTPOeC5y8DO0zuV1mqCk/edit?ts=5ed8d6e0)
it's more straightforward to just rename the module.

The PRs did all the heavy lifting, the number of other in-flight PRs affected by this is pretty minimal, and sticking with the workaround is causing problems currently just pushed to downstream packagers.

Please reconsider, also cc @dak1n1 @aareet .

**Pull request closed without merging**
