### PR TITLE
updated docs to show 'excludes' param

### PR DESCRIPTION
**Pull request by AzySir**
Updated Documents to show the "excludes" parameter exists

### CODE REVIEW

**Comment by AzySir** [comment]
@findkim Hey Kim, are we able to get this reviewed and merge if possible please!! - Thanks :)

**Comment by Spaider** [comment]
@AzySir documentation on `excludes` is rather concise. There are no examples on regex'es. E.g. I did not find a way to exclude the same dir on any nested level (`__pycache__` for Python deployments).
Is there a way to achieve this? 

Thanks

**Comment by AzySir** [comment]
@Spaider what was the parameter you added - could you share some code?

**Comment by Spaider** [comment]
Here's zip archive definition for AppEngine package with Flask App, written in Python:
```
data "archive_file" "app_package" {
  type = "zip"
  source_dir = "../python/"
  output_path = "../.deploy/app.zip"
  excludes = ["__pycache__", ".DS_Store"]
}
```
This way it excludes only top-level `__pycache__` directory but not the the directories with the same name but on nested levels down below.

**Comment by AzySir** [comment]
Not sure on directories to be honest... Isn't __pycache__ a folder? 
Is the ".DS_Store" working?

```
excludes = ["__pycache__/*"]
excludes = ["./__pycache__ "]
```

**Comment by Spaider** [comment]
Please disregard `.DS_Store`. It is a file with some macOS garbage.
Unfortunately, neither options for ignoring `__pycache__` directory worked out.

**Comment by AzySir** [comment]
@Spaider that's a fair use case. Unfortunately I don't have an answer for you - also I didn't design the functionality. I just created a documentation PR.

I think you want to keep an eye on these (and maybe raise your own) -

Here they are asking for a "**/.git" of set up. 
[https://github.com/hashicorp/terraform-provider-archive/issues/62](https://github.com/hashicorp/terraform-provider-archive/issues/62)

**Comment by raymondhardynike** [comment]
You can see some examples in the test. Glob/wildcards are not supported. I used to have full regex support when i first added excludes but was asked to change it to what it is today. It just uses relative paths. So you would have to list all of the sub dirs one at a time.

**Comment by raymondhardynike** [comment]
It just checks if relname matches elements in the excludes list.
line 74 of zip_archiver.go
for _, exclude := range excludes {
		if exclude == "" {
			continue
		}

		if exclude == fileName {
			return true
		}
	}
	return false

**Comment by manasouza** [comment]
@AzySir and @Spaider please take a look at https://github.com/hashicorp/terraform-provider-archive/pull/57 if that could be of any help

**Review by Dezzj — COMMENTED** [review]
Veiwed

**Pull request merged**
