### PR TITLE
Add more hash outputs of archive content

### PR DESCRIPTION
**Pull request by zachwhaley**
Per https://github.com/hashicorp/terraform-provider-local/issues/137 this brings the provider up to feature parity with all of Terraform's built-in file-reading functions

The following outputs are added to `data_archive_file`:

* `output_sha256` - SHA256 checksum of archive content.
* `output_sha512` - SHA512 checksum of archive content.
* `output_base64sha512` - Base64 encoded SHA512 checksum of archive content.

### CODE REVIEW

**Comment by bookshelfdave** [comment]
hi @zachwhaley thank you for the PR! The team is strongly focused on some project work for the next few weeks, but I'm adding it to our board to review when we have some free cycles.

**Comment by zachwhaley** [comment]
@bookshelfdave Any updates?

**Comment by bookshelfdave** [comment]
@zachwhaley folks are back from PTO next week and we'll take a look then.

**Comment by bookshelfdave** [comment]
Hello @zachwhaley - my apologies for the delay in getting these reviewed. Our team synced up with the Terraform Core engineers and discussed this PR. As currently implemented, users will need to apply changes twice on updates before they are realized in downstream resources/outputs/etc. 

This issue can be solved by using a [CustomizeDiff](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/customizing-differences), so the plan also sees the expected value changes, which in turn any references can also see those value changes at the same time.

However, both local and archive providers are scheduled to be migrated to the Terraform Plugin Framework this quarter, and we have a strong preference to implement this feature using [attribute plan modifiers](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification) with the framework.

For now, we are going to hold off on bringing these changes in. Our plan is to reevaluate this once the migration to the plugin framework is complete.

**Comment by zachwhaley** [comment]
Thanks @bookshelfdave !

Is there anything I can follow to know when these changes are being worked on or completed?

**Comment by bendbennett** [comment]
> Thanks @bookshelfdave !
> 
> Is there anything I can follow to know when these changes are being worked on or completed?

@zachwhaley the issue for tracking migration to the Terraform Plugin Framework is #112

**Comment by zachwhaley** [comment]
@bendbennett I've pulled in the latest changes from the main branch.  Let me know if there are any other changes I need to make.  Thanks!

**Comment by bendbennett** [comment]
Thanks @zachwhaley, we'll review this shortly.

**Review by bendbennett — COMMENTED** [review]
LGTM @zachwhaley 

Could you update the tests for the archive resource in same way that you have done for the data source?

**Comment by zachwhaley** [comment]
> LGTM @zachwhaley
> 
> Could you update the tests for the archive resource in same way that you have done for the data source?

@bendbennett Sure thing!  I hadn't updated the tests because that resource is deprecated.  I only updated the source code because the builds were failing.

**Review by bendbennett — APPROVED** [review]
LGTM 👍 

Many thanks for your contribution @zachwhaley

**Pull request merged**
